plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
markdown: kramdown
collections:
  book:
    output: true
  external:
    output: true
  examples:
    output: true
  tutorial:
    output: true
  services:
    output: true
  concepts: 
    output: true
  resources:
    output: true
  faq:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

twitter:
  username: OSGiAlliance

google_analytics: UA-801425-1

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - 'run.sh'
  - '.travis.yml'
  - '/vendor'
